controller_list:
  - name: fake_arm_1_controller
    type: $(arg fake_execution_type)
    joints:
      - j_torso_1
      - j_arm_1_1
      - j_arm_1_2
      - j_arm_1_3
      - j_arm_1_4
      - j_arm_1_5
      - j_arm_1_6
      - j_arm_1_7
  - name: fake_arm_2_controller
    type: $(arg fake_execution_type)
    joints:
      - j_torso_1
      - j_arm_2_1
      - j_arm_2_2
      - j_arm_2_3
      - j_arm_2_4
      - j_arm_2_5
      - j_arm_2_6
      - j_arm_2_7
  - name: fake_both_arms_controller
    type: $(arg fake_execution_type)
    joints:
      - j_torso_1
      - j_arm_1_1
      - j_arm_1_2
      - j_arm_1_3
      - j_arm_1_4
      - j_arm_1_5
      - j_arm_1_6
      - j_arm_1_7
      - j_arm_2_1
      - j_arm_2_2
      - j_arm_2_3
      - j_arm_2_4
      - j_arm_2_5
      - j_arm_2_6
      - j_arm_2_7
  - name: fake_torso_controller
    type: $(arg fake_execution_type)
    joints:
      - j_torso_1
  - name: fake_sliding_guide_controller
    type: $(arg fake_execution_type)
    joints:
      - j_sliding_guide
initial:  # Define initial robot poses per group
  - group: arm_1
    pose: home
  - group: arm_2
    pose: home
  - group: both_arms
    pose: home
  - group: torso
    pose: home
  - group: sliding_guide
    pose: right_end