joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

arm_1_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - j_arm_1_1
    - j_arm_1_2
    - j_arm_1_3
    - j_arm_1_4
    - j_arm_1_5
    - j_arm_1_6
    - j_arm_1_7
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.0
      arm_1_joint1: {trajectory: 0.1, goal: 0.1}
      arm_1_joint2: {trajectory: 0.1, goal: 0.1}
      arm_1_joint3: {trajectory: 0.1, goal: 0.1}
      arm_1_joint4: {trajectory: 0.1, goal: 0.1}
      arm_1_joint5: {trajectory: 0.1, goal: 0.1}
      arm_1_joint6: {trajectory: 0.1, goal: 0.1}
      arm_1_joint7: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

arm_2_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - j_arm_2_1
    - j_arm_2_2
    - j_arm_2_3
    - j_arm_2_4
    - j_arm_2_5
    - j_arm_2_6
    - j_arm_2_7
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.0
      arm_2_joint1: {trajectory: 0.1, goal: 0.1}
      arm_2_joint2: {trajectory: 0.1, goal: 0.1}
      arm_2_joint3: {trajectory: 0.1, goal: 0.1}
      arm_2_joint4: {trajectory: 0.1, goal: 0.1}
      arm_2_joint5: {trajectory: 0.1, goal: 0.1}
      arm_2_joint6: {trajectory: 0.1, goal: 0.1}
      arm_2_joint7: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
