controller_list:
  - name: arm_1_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - j_arm_1_1
      - j_arm_1_2
      - j_arm_1_3
      - j_arm_1_4
      - j_arm_1_5
      - j_arm_1_6
      - j_arm_1_7
  - name: arm_2_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - j_arm_2_1
      - j_arm_2_2
      - j_arm_2_3
      - j_arm_2_4
      - j_arm_2_5
      - j_arm_2_6
      - j_arm_2_7
  - name: torso_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - j_torso_1
  - name: both_arms_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - j_arm_1_1
      - j_arm_1_2
      - j_arm_1_3
      - j_arm_1_4
      - j_arm_1_5
      - j_arm_1_6
      - j_arm_1_7
      - j_arm_2_1
      - j_arm_2_2
      - j_arm_2_3
      - j_arm_2_4
      - j_arm_2_5
      - j_arm_2_6
      - j_arm_2_7
  - name: sliding_guide_traj_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - j_sliding_guide