controller_list:
  - name: fake_arm_1_controller
    type: $(arg fake_execution_type)
    joints:
      - j_arm_1_1
      - j_arm_1_1
      - j_arm_1_1
      - j_arm_1_1
      - j_arm_1_1
      - j_arm_1_1
      - j_arm_1_1
  - name: fake_arm_2_controller
    type: $(arg fake_execution_type)
    joints:
      - j_arm_2_1
      - j_arm_2_1
      - j_arm_2_1
      - j_arm_2_1
      - j_arm_2_1
      - j_arm_2_1
      - j_arm_2_1
  - name: fake_both_arms_controller
    type: $(arg fake_execution_type)
    joints:
      - j_arm_2_1
      - j_arm_2_1
      - j_arm_2_1
      - j_arm_2_1
      - j_arm_2_1
      - j_arm_2_1
      - j_arm_2_1
      - j_arm_1_1
      - j_arm_1_1
      - j_arm_1_1
      - j_arm_1_1
      - j_arm_1_1
      - j_arm_1_1
      - j_arm_1_1
initial:  # Define initial robot poses per group
  - group: arm_l
    pose: home
  - group: arm_r
    pose: home
  - group: both_arms
    pose: home