# Publish joint_states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

joint_trajectory_controller:
  type: joint_trajectory_controller/JointTrajectoryController
  publish_rate: 50
