joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

arm_l_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - j_arm_1_1
    - j_arm_1_1
    - j_arm_1_1
    - j_arm_1_1
    - j_arm_1_1
    - j_arm_1_1
    - j_arm_1_1
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.0
      arm_1_1: {trajectory: 0.1, goal: 0.1}
      arm_1_2: {trajectory: 0.1, goal: 0.1}
      arm_1_3: {trajectory: 0.1, goal: 0.1}
      arm_1_4: {trajectory: 0.1, goal: 0.1}
      arm_1_5: {trajectory: 0.1, goal: 0.1}
      arm_1_6: {trajectory: 0.1, goal: 0.1}
      arm_1_7: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

arm_r_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - j_arm_2_1
    - j_arm_2_1
    - j_arm_2_1
    - j_arm_2_1
    - j_arm_2_1
    - j_arm_2_1
    - j_arm_2_1
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.0
      arm_2_1: {trajectory: 0.1, goal: 0.1}
      arm_2_2: {trajectory: 0.1, goal: 0.1}
      arm_2_3: {trajectory: 0.1, goal: 0.1}
      arm_2_4: {trajectory: 0.1, goal: 0.1}
      arm_2_5: {trajectory: 0.1, goal: 0.1}
      arm_2_6: {trajectory: 0.1, goal: 0.1}
      arm_2_7: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
    