controller_list:
  - name: arm_l_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - j_arm_1_1
      - j_arm_1_1
      - j_arm_1_1
      - j_arm_1_1
      - j_arm_1_1
      - j_arm_1_1
      - j_arm_1_1
  - name: arm_r_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - j_arm_2_1
      - j_arm_2_1
      - j_arm_2_1
      - j_arm_2_1
      - j_arm_2_1
      - j_arm_2_1
      - j_arm_2_1