# link0_coll:

#   coll_radius: 0.07

link1_coll:

  coll_radius: 0.07

link2_coll:

  coll_radius: 0.053

link3_coll:

  coll_radius: 0.08

link4_coll:

  coll_radius: 0.08

link5_coll:
  
  coll_radius: 0.06

link6_coll:
  
  coll_radius: 0.08

link7_coll:

  coll_radius: 0.05