joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    
arm_1_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm_1_joint_1
    - arm_1_joint_2
    - arm_1_joint_3
    - arm_1_joint_4
    - arm_1_joint_5
    - arm_1_joint_6
    - arm_1_joint_7
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.0   #if this is anything but 0, the motion planning will abort with "goal tolerance violated" for no reason
    arm_1_joint1: {trajectory: 0.1, goal: 0.1}
    arm_1_joint2: {trajectory: 0.1, goal: 0.1}
    arm_1_joint3: {trajectory: 0.1, goal: 0.1}
    arm_1_joint4: {trajectory: 0.1, goal: 0.1}
    arm_1_joint5: {trajectory: 0.1, goal: 0.1}
    arm_1_joint6: {trajectory: 0.1, goal: 0.1}
    arm_1_joint7: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
    
arm_2_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm_2_joint_1
    - arm_2_joint_2
    - arm_2_joint_3
    - arm_2_joint_4
    - arm_2_joint_5
    - arm_2_joint_6
    - arm_2_joint_7
  constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.0
        arm_2_joint1: {trajectory: 0.1, goal: 0.1}
        arm_2_joint2: {trajectory: 0.1, goal: 0.1}
        arm_2_joint3: {trajectory: 0.1, goal: 0.1}
        arm_2_joint4: {trajectory: 0.1, goal: 0.1}
        arm_2_joint5: {trajectory: 0.1, goal: 0.1}
        arm_2_joint6: {trajectory: 0.1, goal: 0.1}
        arm_2_joint7: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

hand_1_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - right_hand_v2s_synergy_joint
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

hand_2_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_hand_v2s_synergy_joint
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10