left_hand_v1_2_research:
  gazebo_ros_control:
    pid_gains:
      # palm
      left_hand_v1_2_research_palm_central_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      left_hand_v1_2_research_palm_central_thumb_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      # thumb
      left_hand_v1_2_research_thumb_knuckle_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      left_hand_v1_2_research_thumb_proximal_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      left_hand_v1_2_research_thumb_distal_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      # index
      left_hand_v1_2_research_index_knuckle_joint:
        p: 0.0
        i: 0.0
        d: 10.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      left_hand_v1_2_research_index_proximal_joint:
        p: 0.0
        i: 0.0
        d: 10.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      left_hand_v1_2_research_index_middle_joint:
        p: 0.0
        i: 0.0
        d: 10.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      left_hand_v1_2_research_index_distal_joint:
        p: 0.0
        i: 0.0
        d: 10.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      # middle
      left_hand_v1_2_research_middle_knuckle_joint:
        p: 0.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      left_hand_v1_2_research_middle_proximal_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      left_hand_v1_2_research_middle_middle_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      left_hand_v1_2_research_middle_distal_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      # ring
      left_hand_v1_2_research_ring_knuckle_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      left_hand_v1_2_research_ring_proximal_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      left_hand_v1_2_research_ring_middle_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      left_hand_v1_2_research_ring_distal_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      # little
      left_hand_v1_2_research_little_knuckle_joint:
        p: 1.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      left_hand_v1_2_research_little_proximal_joint:
        p: 1.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      left_hand_v1_2_research_little_middle_joint:
        p: 1.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      left_hand_v1_2_research_little_distal_joint:
        p: 1.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true

# right hand
right_hand_v1_2_research:
  gazebo_ros_control:
    pid_gains:
      # thumb
      right_hand_v1_2_research_thumb_knuckle_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      right_hand_v1_2_research_thumb_proximal_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      right_hand_v1_2_research_thumb_distal_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      # index
      right_hand_v1_2_research_index_knuckle_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      right_hand_v1_2_research_index_proximal_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      right_hand_v1_2_research_index_middle_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      right_hand_v1_2_research_index_distal_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      # middle
      right_hand_v1_2_research_middle_knuckle_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      right_hand_v1_2_research_middle_proximal_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      right_hand_v1_2_research_middle_middle_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      right_hand_v1_2_research_middle_distal_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      # ring
      right_hand_v1_2_research_ring_knuckle_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      right_hand_v1_2_research_ring_proximal_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true 
      right_hand_v1_2_research_ring_middle_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      right_hand_v1_2_research_ring_distal_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true 
      # littlei_clamp: 0.2
      right_hand_v1_2_research_little_knuckle_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      right_hand_v1_2_research_little_proximal_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      right_hand_v1_2_research_little_middle_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      right_hand_v1_2_research_little_distal_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
