<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- File defining a macro for generating the collision links for the RePair platform -->
<!-- load_sol = true is used when the wrist auxiliary d.o.f. (used inside the optimization) has to be
removed -->

<xacro:macro name="repair_arm_coll" params="load_sol" />

<joint name="arm_${id}_link_1_coll_joint" type="fixed">

    <origin xyz="${link1_coll_offset_x} ${link1_coll_offset_y} ${link1_coll_offset_z}" rpy="0 0 0"/>

    <parent link="arm_${id}_link_1"/>

    <child link="arm_${id}_link1_coll"/>

</joint>

<link name="arm_${id}_link1_coll">

    <visual name="arm_${id}_link1_coll_visual">

            <origin xyz="0 0 0" rpy="0 0 0"/>

            <geometry>
                <sphere radius="${coll_radius_link1}"/>
            </geometry>

            <material name="darkred"/>

    </visual>

</link>

<joint name="arm_${id}_link_2_coll_joint" type="fixed">

    <origin xyz="${link2_coll_offset_x} ${link2_coll_offset_y} ${link2_coll_offset_z}" rpy="0 0 0"/>

    <parent link="arm_${id}_link_2"/>

    <child link="arm_${id}_link2_coll"/>

</joint>

<link name="arm_${id}_link2_coll">

    <visual name="arm_${id}_link2_coll_visual">

            <origin xyz="0 0 0" rpy="0 0 0"/>

            <geometry>
                <sphere radius="${coll_radius_link2}"/>
            </geometry>

            <material name="darkred"/>

    </visual>

</link>

<joint name="arm_${id}_link_3_coll_joint" type="fixed">

    <origin xyz="${link3_coll_offset_x} ${link3_coll_offset_y} ${link3_coll_offset_z}" rpy="0 0 0"/>

    <parent link="arm_${id}_link_3"/>

    <child link="arm_${id}_link3_coll"/>

</joint>

<link name="arm_${id}_link3_coll">

    <visual name="arm_${id}_link3_coll_visual">

            <origin xyz="0 0 0" rpy="0 0 0"/>

            <geometry>
                <sphere radius="${coll_radius_link3}"/>
            </geometry>

            <material name="darkred"/>

    </visual>

</link>

<joint name="arm_${id}_link_4_coll_joint" type="fixed">

    <origin xyz="${link4_coll_offset_x} ${link4_coll_offset_y} ${link4_coll_offset_z}" rpy="0 0 0"/>

    <parent link="arm_${id}_link_4"/>

    <child link="arm_${id}_link4_coll"/>

</joint>

<link name="arm_${id}_link4_coll">

    <visual name="arm_${id}_link4_coll_visual">

            <origin xyz="0 0 0" rpy="0 0 0"/>

            <geometry>
                <sphere radius="${coll_radius_link4}"/>
            </geometry>

            <material name="darkred"/>

    </visual>

</link>

<xacro:if value="${load_sol == True}">

    <joint name="arm_${id}_link_5_coll_joint" type="fixed">

        <origin xyz="${link5_coll_offset_x + wrist_off} ${link5_coll_offset_y} ${link5_coll_offset_z}" rpy="0 0 0"/>

        <parent link="arm_${id}_link_5"/>

        <child link="arm_${id}_link5_coll"/>

    </joint>

</xacro:if>
<xacro:unless value="${load_sol == True}">

    <joint name="arm_${id}_link_5_coll_joint" type="prismatic">

        <origin xyz="${link5_coll_offset_x } ${link5_coll_offset_y} ${link5_coll_offset_z}" rpy="0 0 0"/>

        <parent link="arm_${id}_link_5"/>

        <child link="arm_${id}_link5_coll"/>

        <limit lower="${0}" upper="${sliding_wrist_deltaz_ub}" effort="${big_tau_max}" velocity="10.0"/>

        <axis xyz="1 0 0"/>

    </joint>

</xacro:unless>


<link name="arm_${id}_link5_coll">

    <visual name="arm_${id}_link5_coll_visual">

            <geometry>
                <sphere radius="${coll_radius_link5}"/>
            </geometry>

            <material name="darkred"/>

    </visual>

</link>

<joint name="arm_${id}_link_6_coll_joint" type="fixed">

    <origin xyz="${link6_coll_offset_x} ${link6_coll_offset_y} ${link6_coll_offset_z}" rpy="0 0 0"/>

    <parent link="arm_${id}_link_6"/>

    <child link="arm_${id}_link6_coll"/>

</joint>

<link name="arm_${id}_link6_coll">

    <visual name="arm_${id}_link6_coll_visual">

            <geometry>
                <sphere radius="${coll_radius_link6}"/>
            </geometry>

            <material name="darkred"/>

    </visual>

</link>


<joint name="arm_${id}_link7_coll_joint" type="fixed">

    <origin xyz="${link7_coll_offset_x} ${link7_coll_offset_y} ${link7_coll_offset_z}" rpy="0 0 0"/>

    <parent link="arm_${id}_link_7"/>

    <child link="arm_${id}_link7_coll"/>

</joint>

<link name="arm_${id}_link7_coll">

        <visual name="arm_${id}_link7_coll_visual">

                <geometry>
                    <sphere radius="${coll_radius_link7}"/>
                </geometry>

                <material name="darkred"/>

        </visual>

</link>

</robot>