use_both_hands: False #Indicates if bimanula manipulation should be used
use_hands: True #Indicates if QB hands should be used at all (Per default True)
grasp_without_rotation: True # Indicates if we use oriented bounding box from recognition framework to align hand
follow_the_hand: True # it will choose placement side based on the hand and not on the published data
use_klampt: True #uses Klampt instead of Moveit

min_z_value_arm_1: 1.05 # Minimum Z value the Left (big hand) arm is alowed to go down to
min_z_value_arm_2: 1.076 # Minimum Z value the Right (small hand) arm is alowed to go down to
  
fresco_pose_world_y_offset: 0.1348 # Offset in Y direction for correct Hand placement above Fresco fragment (we still don't know why we need it)

fresco_pose_world_z: 1.29 # Initial Z Heigt for placing Hand above Fresco Fragment

fresco_down_pose_y_offset: 0.04 # Hardcoded Y offset to better grasp fresco when going down to it

placement_center_table_x: -0.1 # Placing offset to not collide with other already placed frescos
placement_center_table_y: 0.5 # Placing offset to not collide with other already placed frescos

lift_position_z_offset_after_grasp: 0.16 # intermediate position after grasping to go to, to test if grasp was succesfull

dropping_position_z_arm_1: 1.15 # Z height at which the hand opens tro drop the fresco
dropping_position_z_arm_2: 1.1

qbHand_current_thresh: 100 # current threshold to check if fresco was properly grasped

# LEGACY
use_pyrealsense: False #Legacy, indicates if pyrealsense library should be used
use_fragment_alignment: False #Legacy, indicates if hand sould be aligned fresco bounding box
hardcoded_placement: False #Legacy, indicates if we use hardcoded placing position for fresco