joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    
arm_1_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - j_torso_1
    - j_arm_1_1
    - j_arm_1_2
    - j_arm_1_3
    - j_arm_1_4
    - j_arm_1_5
    - j_arm_1_6
    - j_arm_1_7
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.0   #if this is anything but 0, the motion planning will abort with "goal tolerance violated" for no reason
    j_torso_1: { trajectory: 0.1, goal: 0.1 }
    j_arm_1_1: { trajectory: 0.1, goal: 0.1 }
    j_arm_1_2: { trajectory: 0.1, goal: 0.1 }
    j_arm_1_3: { trajectory: 0.1, goal: 0.1 }
    j_arm_1_4: { trajectory: 0.1, goal: 0.1 }
    j_arm_1_5: { trajectory: 0.1, goal: 0.1 }
    j_arm_1_6: { trajectory: 0.1, goal: 0.1 }
    j_arm_1_7: { trajectory: 0.1, goal: 0.1 }
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  gains:
    j_torso_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_arm_1_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_arm_1_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_arm_1_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_arm_1_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_arm_1_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_arm_1_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_arm_1_7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1


arm_2_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - j_torso_1
    - j_arm_2_1
    - j_arm_2_2
    - j_arm_2_3
    - j_arm_2_4
    - j_arm_2_5
    - j_arm_2_6
    - j_arm_2_7
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.0
    j_torso_1: {trajectory: 0.1, goal: 0.1}
    j_arm_2_1: {trajectory: 0.1, goal: 0.1}
    j_arm_2_2: {trajectory: 0.1, goal: 0.1}
    j_arm_2_3: {trajectory: 0.1, goal: 0.1}
    j_arm_2_4: {trajectory: 0.1, goal: 0.1}
    j_arm_2_5: {trajectory: 0.1, goal: 0.1}
    j_arm_2_6: {trajectory: 0.1, goal: 0.1}
    j_arm_2_7: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  gains:
    j_torso_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_arm_2_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_arm_2_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_arm_2_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_arm_2_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_arm_2_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_arm_2_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_arm_2_7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

torso_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - j_torso_1
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.0
    j_torso_1: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  gains:
    j_torso_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

# sliding_guide_traj_controller:
#   type: position_controllers/JointTrajectoryController
#   joints:
#     - j_sliding_guide
#   constraints:
#     goal_time: 0.6
#     stopped_velocity_tolerance: 0.0
#     j_sliding_guide: {trajectory: 0.1, goal: 0.1}
#   gains:
#     j_sliding_guide:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1